### PR TITLE
#24 share button

### PR DESCRIPTION
**Pull request by Yanan-G**
Clicking on the Share button will pop up a modal where users can type their tuit content in. For now, it will only create a new tuit with the text provided. I'm still trying to figure out a way to get the reference to the snippet so that it gets attached to the tuit. Any ideas how to achieve that?

Screen Shot 2022-04-18 at 8 36 11 PM

### CODE REVIEW

**Comment by ghackford** [comment]
I think we need to figure out how to display the user's snippets properly on that screen, since currently those snippets are just test JSON objects. The real snippet objects should have object ID's that we can lift and hook into the new Tuit.

**Comment by NickyL279** [comment]
I’m thinking about rendering the snippets after all the tuits

From: ghackford ***@***.***>
Date: Monday, April 18, 2022 at 21:14
To: osbornnick/Tuiter ***@***.***>
Cc: zliu ***@***.***>, Review requested ***@***.***>
Subject: Re: [osbornnick/Tuiter] #24 share button (PR #30)

I think we need to figure out how to display the user's snippets properly on that screen, since currently those snippets are just test JSON objects. The real snippet objects should have object ID's that we can lift and hook into the new Tuit.

**Comment by osbornnick** [comment]
when creating a new tuit, just include the `snippet._id` as the `snippet` field on the tuit! I added

**Review by osbornnick — APPROVED** [review]
looks like it works!

**Pull request merged**
